# Generated by Django 2.2 on 2019-05-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobservice.Person'),
        ),
    ]
