# Generated by Django 2.2 on 2019-05-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='userName',
            new_name='person',
        ),
    ]
