# Generated by Django 2.2 on 2019-05-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='', max_length=50)),
                ('companyMail', models.EmailField(default='', max_length=254)),
                ('companyPassword', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='content',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='additionalSkills',
            field=models.CharField(default='', max_length=105),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='jobPosition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='location',
            field=models.CharField(default='', max_length=105),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='proffesion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='trade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='companyName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobservice.Company'),
            preserve_default=False,
        ),
    ]
