# Generated by Django 2.2 on 2019-05-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobservice', '0002_auto_20190521_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='trade',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='joboffer',
            old_name='additionalInfo',
            new_name='jobDescription',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='additionalSkills',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='ExperienceLevel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='jobType',
            field=models.CharField(default='', max_length=50),
        ),
    ]
