# Generated by Django 2.2 on 2019-05-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobservice', '0004_auto_20190504_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackanswer',
            name='idReplyToOffer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobservice.ReplyToOffer'),
        ),
        migrations.AlterField(
            model_name='feedbackanswer',
            name='accept',
            field=models.BooleanField(default='', max_length=50),
        ),
    ]
