# Generated by Django 2.2 on 2019-05-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobservice', '0004_auto_20190523_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='jobDescription',
            field=models.TextField(),
        ),
    ]
