# Generated by Django 2.2 on 2019-05-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobservice', '0005_auto_20190504_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='nameCv',
        ),
        migrations.RemoveField(
            model_name='feedbackanswer',
            name='idReplyToOffer',
        ),
        migrations.RemoveField(
            model_name='feedbackanswer',
            name='response',
        ),
        migrations.RemoveField(
            model_name='replytooffer',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='replytooffer',
            name='messForCompany',
        ),
        migrations.AlterField(
            model_name='cv',
            name='userName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobservice.Person'),
        ),
        migrations.AlterField(
            model_name='feedbackanswer',
            name='accept',
            field=models.CharField(default='', max_length=50),
        ),
    ]
