# Generated by Django 2.2 on 2019-05-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobservice', '0007_auto_20190505_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='nameCv',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='idReplyToOffer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobservice.ReplyToOffer'),
        ),
        migrations.AddField(
            model_name='replytooffer',
            name='cv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobservice.Cv'),
        ),
        migrations.AddField(
            model_name='replytooffer',
            name='messForCompany',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='feedbackanswer',
            name='accept',
            field=models.BooleanField(default='', max_length=50),
        ),
    ]
