# Generated by Django 2.2 on 2019-05-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobservice', '0008_auto_20190505_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='additionalInfo',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='cv',
            name='dateOfBirth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cv',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experience',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='cv',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cv',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cv',
            name='nameCv',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cv',
            name='placeOfResidence',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='additionalSkills',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='location',
            field=models.CharField(default='', max_length=300),
        ),
    ]
